### PR TITLE
Use MultipleAlignment DS as a symmetry return

### PR DESCRIPTION
**Pull request by lafita**
Optimization with gaps requires returning a MultipleAlignment to describe the symmetry. Because of that, all the post-analysis code has been adapted to deal with the new data structure.

New feature: in development, a recursive version of CeSymm that can identify multiple axis.

### CODE REVIEW

**Comment by andreasprlic** [comment]
travis has some failures, can you take a look?

**Comment by lafita** [comment]
Travis always fails for the symmetry project, it seems a downloading error (with biojava). @sbliven do you know the exact reason? 
We always install it locally to ensure that it compiles properly before doing a pull request. I tried with this one and everything is OK.

**Comment by sbliven** [comment]
Travis hasn't worked since Cole moved nexus behind the firewall. To fix it we need to remove the dependency on ava.

**Comment by sbliven** [comment]
See #30

**Pull request merged**
