### PR TITLE
Master

### PR DESCRIPTION
**Pull request by lafita**
Summary of the changes:
- CeSymm: the align method performs multiple alignments blacking out previous alignments.
- CESymmParameters: added the RefineMethod and maxNrSubunits variables, exposed to the UI.
- Package refine: implements the RefinerMethods. By now there are two possible methods: SINGLE (only one alignment) or MULTIPLE (multiple alignments).

In progress: 
- Multiple Alignment of the subunits.
- Visualization of the 3D superposition.
- Parameters for controlling: subunit colors, rotation number (equivalent to angle).
- Jmol visualization: show the rotation axis and show only model 1 as default.

### CODE REVIEW

**Comment by sbliven** [comment]
Do we need to blank out the break flag in the MatrixListener you implemented?

**Comment by sbliven** [comment]
Does the running time analysis code in SubunitTools.java belong in the core part of CE-Symm?

If so, we should remove the hard-coded paths for the output locations.

**Comment by lafita** [comment]
The matrix mat contains the information of the blackout from the OrigM matrix, but it is recalculated each optimization iteration with the residue distances. The matrix listener keeps the entries blacked out in this case. 
The break flag matrix, however, is initialized each iteration and the entries calculated depending on the values in mat, so I deduce that if the matrix mat is blacked out the break flag also acquires the information.

Adding the matrix listener only for mat seems to solve the problem (alignments falling inside the blacked out region) for the structures analysed so far.

**Comment by lafita** [comment]
The code inside the subunit package that belonged in the core part of CE-Symm has been moved to the corresponding places. The code that is left only saves parts of the calculation for external analysis (like graphs, fasta alignments or running times). I will consider moving this methods to some other I/O package if they become important.

I have changed the hard coded paths and set them as input of the methods.

**Pull request merged**
