### PR TITLE
Create FASTA writer for QuatSymm multiple alignment

### PR DESCRIPTION
**Pull request by lafita**
Address issue #99

### CODE REVIEW

**Comment by lafita** [comment]
There is some error related to source.rcsb.org - I will have a look and fix tests using the website.

**Comment by josemduarte** [comment]
Nice, thanks @lafita 

As you noted all access to source.rcsb.org should be discontinued as soon as possible. We are going to be shutting down the service soon. See the related PR in biojava: https://github.com/biojava/biojava/pull/882

**Comment by lafita** [comment]
Thanks @josemduarte 

Would this be fixed by updating to the next BioJava release? 
SCOP identifiers are still available through the StructureIdentifier interface right?

**Comment by josemduarte** [comment]
> Would this be fixed by updating to the next BioJava release?

That should do it. I hope it doesn't take too long for the next release to come.

> SCOP identifiers are still available through the StructureIdentifier interface right?

Yes, the Berkeley provider is available but it is slow to initialise.

**Comment by lafita** [comment]
Ok, in that case I am going to merge this and we can fix the test issues (unrelated to this PR) when we have a new BioJava version.

**Comment by josemduarte** [comment]
@lafita regarding new BioJava version and the code I'm removing in https://github.com/biojava/biojava/pull/882, it'd be a good idea to build this project using that biojava branch's snapshot and see if everything is alright. That is to confirm I didn't remove any needed functionality.

**Comment by josemduarte** [comment]
@lafita I've tried with biojava with the PR branch https://github.com/biojava/biojava/pull/882 and the project built correctly including tests.

**Comment by lafita** [comment]
Thanks @josemduarte I am merging it then.

**Pull request merged**
